### ISSUE TITLE
x64 availability, 

### ISSUE THREAD

**Issue by frett27** [AdaCore/win32ada#2]
Are there any x64 binding for windows ?

**Comment by Entomy** [comment]
To answer on behalf of AdaCore since they didn't: This is just a thin binding not marshalling code, so with a 64-bit compiler it will bind against the x64 libraries. Many things are defined using standard attributes so it will use the right sizes as appropriate. 
![image](https://user-images.githubusercontent.com/25399505/59440252-a7cf5500-8dc4-11e9-8375-48a046a19b3d.png)

**Comment by frett27** [comment]
My tests show it didn't out of the box, by now. But with this new perspective it perhaps worth an investigation. I needed it for sound system. Without deep insights i switched to a portable library (soundio).
